name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: docker build -t ks4556737540/upload:latest .

    - name: Push Docker image to Docker Hub
      run: docker push ks4556737540/upload:latest

    - name: Deploy on EC2 via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.AWS_EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
        script: |
          sudo docker pull ks4556737540/upload:latest
          sudo docker stop app || true
          sudo docker rm app || true
          sudo docker run -d --name app -p 80:3000 ks4556737540/upload:latest
